name: Preview URL Checks

on:
  deployment_status:

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  lighthouse:
    # if: github.event_name == 'deployment_status'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Run Lighthouse
    steps:
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: '${{ github.event.deployment_status.target_url }}, ${{ github.event.deployment_status.target_url }}/writing, ${{ github.event.deployment_status.target_url }}/mocking-fetch'
          outputDirectory: /tmp/artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: Lighthouse reports
          path: /tmp/artifacts

  playwright:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment.environment != 'production'
    timeout-minutes: 60

    name: e2e tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
      options: --user 1001
    steps:
      # Set up the repo
      - uses: actions/checkout@v2

        # Set up pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 8

        # Set up Node, use the `pnpm` cache for any dependencies
      - uses: actions/setup-node@v1
        with:
          node-version: 20

        # Install dependencies
      - name: Install NPM dependencies
        run: pnpm install

        # Run end-to-end tests against the deployed preview environment.
      - name: Run end-to-end tests
        run: pnpm e2e
        env:
          TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}

        # Upload any test reports.
      - uses: actions/upload-artifact@main
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30%
